# Generated by Django 2.2.3 on 2019-08-06 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20190801_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('avator', models.ImageField(blank=True, null=True, upload_to='')),
                ('profile', models.TextField()),
                ('career', models.TextField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profiles', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
