"""
Django settings for funiv project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'lgw#&q1loj7b@vi!*6d&6m0r2@!%y_4qou94z!mp$c6^pekq^f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['ec2-13-209-47-199.ap-northeast-2.compute.amazonaws.com', '13.209.47.199', '52.79.115.87']


# Application definition

INSTALLED_APPS = [
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'articles',
    'accounts',
    'storages',
    'upload',
    'mysite',
    'myprofile',
    'follow',
    'chat',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'funiv.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'funiv.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'funiv',
	'USER': 'funiv0708',
	'PASSWORD': 'vjslqm0708',
	'HOST': 'funiv.c2dkcuxuarqg.ap-northeast-2.rds.amazonaws.com',
	'PORT': '3306'
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        
        'OPTION': {'user_attributes': ('email', 'name')},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        # 'OPTIONS': {
        #     # UserAttributeSimilarityValidator: username(id or email) 유사도 체크
        #     # MinimumLengthValidator: 최소 길이
        #     # CommonPasswordValidator: common한 비밀번호 체크, 1000개의 common과 비교
        #     # NumericPasswordValidator: 전부 숫자인 비밀번호 사용 못하게
        # }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# if DEBUG:
#     STATIC_URL = '/static/'
#     STATIC_ROOT = os.path.join(BASE_DIR, 'static')
#     # STATICFILES_DIRS = [ ]
#     # STATICFILES_STORAGE = 'pipeline.storage.PipelineCachedStorage' # Local, 즉 DEBUG=True 일 경우 pipeline 사용

#     MEDIA_URL = '/media/'
#     MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# else:
#     # AWS Setting
#     AWS_REGION = 'ap-northeast-2'
#     AWS_STORAGE_BUCKET_NAME = 'arn:aws:s3:::funiv-storage'
#     AWS_QUERYSTRING_AUTH = False
#     AWS_S3_HOST = 's3.%s.amazonaws.com' % AWS_REGION
#     AWS_ACCESS_KEY_ID = 'AKIA3KV4VDTTY5PAKWYL'
#     AWS_SECRET_ACCESS_KEY = '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'
#     AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME

#     AWS_S3_OBJECT_PARAMETERS = {
#         'CacheControl': 'max-age=86400',
#     }

#     # Static Setting
#     STATIC_URL = "https://%s/" % AWS_S3_CUSTOM_DOMAIN
#     STATICFILES_STORAGE = 'storages.backends.s3boto.S3BotoStorage'
#     # AWS_LOCATION = 'static'
#     # STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
#     # STATIC_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, AWS_LOCATION)

#     #Media Setting
#     MEDIA_URL = "https://%s/" % AWS_S3_CUSTOM_DOMAIN
#     DEFAULT_FILE_STORAGE = 'storages.backends.s3boto.S3BotoStorage'
#     # DEFAULT_FILE_STORAGE = 'funiv.storage_backends.MediaStorage'  # <-- here is where we reference it

# AWS Setting
AWS_REGION = 'ap-northeast-2'
AWS_STORAGE_BUCKET_NAME = 'funiv-storage'
AWS_QUERYSTRING_AUTH = False
AWS_S3_HOST = 's3.%s.amazonaws.com' % AWS_REGION
AWS_ACCESS_KEY_ID = 'AKIA3KV4VDTTY5PAKWYL'
AWS_SECRET_ACCESS_KEY = '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'
AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME

AWS_S3_OBJECT_PARAMETERS = {
'CacheControl': 'max-age=86400',
}

# AWS_STATIC_LOCATION = 'static'
# STATICFILES_STORAGE = 'funiv.storage_backends.StaticStorage'
# STATIC_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, AWS_STATIC_LOCATION)

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

AWS_PUBLIC_MEDIA_LOCATION = 'media/public'
DEFAULT_FILE_STORAGE = 'funiv.storage_backends.PublicMediaStorage'

AWS_PRIVATE_MEDIA_LOCATION = 'media/private'
PRIVATE_FILE_STORAGE = 'funiv.storage_backends.PrivateMediaStorage'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

AUTH_USER_MODEL = 'accounts.User' # '앱label.모델명'

LOGIN_REDIRECT_URL = '/' # 로그인 성공시 이동할 경로
LOGIN_URL = '/accounts/login/' # 로그인 경로
LOGOUT_REDIRECT_URL = '/' # 로그아웃 성공시 이동할 경로

SESSION_COOKIE_AGE = 30 * 60 # 세션 유지시간. 디폴트는 2주. 단위 초.
SESSION_COOKIE_NAME = 'FUNIV' # 세션 이름이 겹치지 않도록 지정.

# 인증메일 날리기 위한 설정
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'funiv0708@gmail.com'
EMAIL_HOST_PASSWORD = 'vjslqm0708'
EMAIL_USE_TLS = True

# Channels
ASGI_APPLICATION = 'funiv.routing.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}
